# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a8df5944dbacff15b68967c520d2d0b6a006beb91a5dda47147cca39c86f7baa49cc5b39f0c241d765df99894ba32dfcdde7ed5b317e17c7dd63d5780c8ceec

test:
  secret_key_base: 13a78415a83bee40140670e7fcca2eb1ef140f0538364cb41520f28f62370776034b89474ef73e83b8167b6863b46eb5b59fc614fdb1cfa626c60d92dfc503d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
